{{- if .Values.controller.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.controller.name }}
  name: {{ .Values.controller.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.controller.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.controller.name }}
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
        - image: {{ .Values.controller.image }}
          imagePullPolicy: {{ .Values.controller.imagePullPolicy }}
          {{- if .Values.controller.args }}
          args: 
          {{- range .Values.controller.args }}
            - {{ . }}
          {{- end }}
          {{- end }}
          name: {{ .Values.controller.name }}
          resources:
            limits:
              cpu: {{ .Values.controller.resources.limits.cpu }}
              memory: {{ .Values.controller.resources.limits.memory }}
            requests:
              cpu: {{ .Values.controller.resources.requests.cpu }}
              memory: {{ .Values.controller.resources.requests.memory }}
      serviceAccountName: {{ .Values.controller.name }}
{{- end }}
